# Generated by Django 4.2.6 on 2023-10-12 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_stafflogin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StaffLogin',
        ),
    ]
